name: Test on any Push event
on: [push, pull_request]
jobs:
  test-all:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04, macos-10.15]
      fail-fast: false
    name: '${{ matrix.os }} testing'
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@master
        name: Clone repository
      - uses: actions/setup-dotnet@1.4.0
        name: Install dotnet
        with:
          dotnet-version: '3.1.101'
      - run: dotnet test
        name: Run test
